// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Autism.Models
{
    public partial class BlogPost
    {
        public BlogPost()
        {
            BlogPostMeta = new HashSet<BlogPostMeta>();
            InverseParent = new HashSet<BlogPost>();
            PostComment = new HashSet<PostComment>();
            Tagpost = new HashSet<Tagpost>();
            Category = new HashSet<Category>();
        }

        public long Id { get; set; }
        public long? AuthorId { get; set; }
        public long? ParentId { get; set; }
        public string Title { get; set; }
        public byte Publised { get; set; }
        public DateTime CreatedAtdate { get; set; }
        public DateTime UpdatedAtdate { get; set; }
        public DateTime PublisedAtdate { get; set; }
        public string Content { get; set; }

        public virtual BlogUser Author { get; set; }
        public virtual BlogPost Parent { get; set; }
        public virtual ICollection<BlogPostMeta> BlogPostMeta { get; set; }
        public virtual ICollection<BlogPost> InverseParent { get; set; }
        public virtual ICollection<PostComment> PostComment { get; set; }
        public virtual ICollection<Tagpost> Tagpost { get; set; }

        public virtual ICollection<Category> Category { get; set; }
    }
}