// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Autism.Models
{
    public partial class Category
    {
        public Category()
        {
            InverseParent = new HashSet<Category>();
            Post = new HashSet<BlogPost>();
        }

        public long Id { get; set; }
        public long ParentId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public virtual Category Parent { get; set; }
        public virtual ICollection<Category> InverseParent { get; set; }

        public virtual ICollection<BlogPost> Post { get; set; }
    }
}