// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Autism.Models
{
    public partial class Publication
    {
        public long Id { get; set; }
        public string EbookCode { get; set; }
        public string BookCode { get; set; }
        public long BookId { get; set; }
        public string BookTitle { get; set; }
        public string AuthorName { get; set; }
        public string Content { get; set; }
    }
}