// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Autism.Models
{
    public partial class ResourceTag
    {
        public long Id { get; set; }
        public string TagName { get; set; }
        public long TagId { get; set; }

        public virtual ResourceCategory Tag { get; set; }
    }
}