// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class BlogUser
    {
        public BlogUser()
        {
            BlogPost = new HashSet<BlogPost>();
        }

        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime RegDate { get; set; }
        public string Intro { get; set; }
        public string Profile { get; set; }

        public virtual ICollection<BlogPost> BlogPost { get; set; }
    }
}