// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ShareProject.Models
{
    public partial class DatabaseAutismContext : DbContext
    {
        public DatabaseAutismContext()
        {
        }

        public DatabaseAutismContext(DbContextOptions<DatabaseAutismContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Table1> Table1 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=DatabaseAutism;Integrated Security=true");

            modelBuilder.Entity<Table1>(entity =>
            {
                entity.Property(e => e.Ink).HasColumnName("ink");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}