// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ShareProject.Models
{
    public partial class DatabaseAutismContext : DbContext
    {
        public DatabaseAutismContext()
        {
        }

        public DatabaseAutismContext(DbContextOptions<DatabaseAutismContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AgeRange> AgeRange { get; set; }
        public virtual DbSet<BlogPost> BlogPost { get; set; }
        public virtual DbSet<BlogPostMeta> BlogPostMeta { get; set; }
        public virtual DbSet<BlogUser> BlogUser { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<EmployAsd> EmployAsd { get; set; }
        public virtual DbSet<EmployLearning> EmployLearning { get; set; }
        public virtual DbSet<EmployTraining> EmployTraining { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<Employment> Employment { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<PostComment> PostComment { get; set; }
        public virtual DbSet<Publication> Publication { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<ResourceAgeRange> ResourceAgeRange { get; set; }
        public virtual DbSet<ResourceAttachment> ResourceAttachment { get; set; }
        public virtual DbSet<ResourceCategory> ResourceCategory { get; set; }
        public virtual DbSet<ResourceTag> ResourceTag { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=DatabaseAutism;Integrated Security=true");

            modelBuilder.Entity<AgeRange>(entity =>
            {
                entity.ToTable("Age.Range");

                entity.Property(e => e.AgeRange1).HasColumnName("AgeRange");

                entity.HasOne(d => d.AgeRange1Navigation)
                    .WithMany(p => p.AgeRange)
                    .HasForeignKey(d => d.AgeRange1)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Age.Range_ToResourceAgeRange");
            });

            modelBuilder.Entity<BlogPost>(entity =>
            {
                entity.Property(e => e.Content)
                    .HasColumnType("text")
                    .HasColumnName("content");

                entity.Property(e => e.CreatedAtdate)
                    .HasColumnType("datetime")
                    .HasColumnName("createdAtdate");

                entity.Property(e => e.ParentId).HasColumnName("parentId");

                entity.Property(e => e.Publised).HasColumnName("publised");

                entity.Property(e => e.PublisedAtdate)
                    .HasColumnType("datetime")
                    .HasColumnName("publisedAtdate");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("title");

                entity.Property(e => e.UpdatedAtdate)
                    .HasColumnType("datetime")
                    .HasColumnName("updatedAtdate");

                entity.HasOne(d => d.Author)
                    .WithMany(p => p.BlogPost)
                    .HasForeignKey(d => d.AuthorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BlogPost_ToBlogUser");

                entity.HasOne(d => d.Parent)
                    .WithMany(p => p.InverseParent)
                    .HasForeignKey(d => d.ParentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BlogPost_ToBlogPost");
            });

            modelBuilder.Entity<BlogPostMeta>(entity =>
            {
                entity.ToTable("BlogPost_meta");

                entity.HasIndex(e => e.Key, "AK_BlogPost_meta_post_Id")
                    .IsUnique();

                entity.Property(e => e.Content)
                    .HasColumnType("text")
                    .HasColumnName("content");

                entity.Property(e => e.Key)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("key");

                entity.Property(e => e.PostId).HasColumnName("post_Id");

                entity.HasOne(d => d.Post)
                    .WithMany(p => p.BlogPostMeta)
                    .HasForeignKey(d => d.PostId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BlogPost_meta_BlogPost");
            });

            modelBuilder.Entity<BlogUser>(entity =>
            {
                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasColumnType("ntext")
                    .HasColumnName("email");

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Intro)
                    .IsRequired()
                    .HasColumnType("text");

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MobileNumber)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("password")
                    .IsFixedLength();

                entity.Property(e => e.Profile)
                    .IsRequired()
                    .HasColumnType("ntext")
                    .HasColumnName("profile");

                entity.Property(e => e.RegDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<Category>(entity =>
            {
                entity.ToTable("category");

                entity.HasIndex(e => e.ParentId, "IX_category_parent");

                entity.Property(e => e.Content)
                    .HasColumnType("text")
                    .HasColumnName("content");

                entity.Property(e => e.ParentId).HasColumnName("parentId");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("title");

                entity.HasOne(d => d.Parent)
                    .WithMany(p => p.InverseParent)
                    .HasForeignKey(d => d.ParentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_category_parent");

                entity.HasMany(d => d.Post)
                    .WithMany(p => p.Category)
                    .UsingEntity<Dictionary<string, object>>(
                        "PostCategory",
                        l => l.HasOne<BlogPost>().WithMany().HasForeignKey("PostId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_post_category_BlogPost"),
                        r => r.HasOne<Category>().WithMany().HasForeignKey("CategoryId").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_post_category_category"),
                        j =>
                        {
                            j.HasKey("CategoryId", "PostId");

                            j.ToTable("post_category");

                            j.IndexerProperty<long>("CategoryId").HasColumnName("categoryId");

                            j.IndexerProperty<long>("PostId").HasColumnName("postId");
                        });
            });

            modelBuilder.Entity<EmployAsd>(entity =>
            {
                entity.ToTable("Employ.ASD");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            modelBuilder.Entity<EmployLearning>(entity =>
            {
                entity.ToTable("Employ.Learning");

                entity.Property(e => e.EndDate).HasColumnType("date");

                entity.Property(e => e.Location).HasMaxLength(100);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.StarDate).HasColumnType("date");
            });

            modelBuilder.Entity<EmployTraining>(entity =>
            {
                entity.ToTable("Employ.Training");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsFixedLength();
            });

            modelBuilder.Entity<Employer>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("address");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("email");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("ntext")
                    .HasColumnName("name");

                entity.Property(e => e.PhoneNumber)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsFixedLength();
            });

            modelBuilder.Entity<Employment>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("ntext");

                entity.HasOne(d => d.EmployLearning)
                    .WithMany(p => p.Employment)
                    .HasForeignKey(d => d.EmployLearningId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Employment_ToEmploy.Learning");

                entity.HasOne(d => d.EmployTrain)
                    .WithMany(p => p.Employment)
                    .HasForeignKey(d => d.EmployTrainId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Employment_ToEmploy.Training");

                entity.HasOne(d => d.Employer)
                    .WithMany(p => p.Employment)
                    .HasForeignKey(d => d.EmployerId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Employment_ToEmployer");
            });

            modelBuilder.Entity<Language>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<PostComment>(entity =>
            {
                entity.ToTable("post_comment");

                entity.Property(e => e.Content)
                    .HasColumnType("text")
                    .HasColumnName("content");

                entity.Property(e => e.CreatedAtdate)
                    .HasColumnType("datetime")
                    .HasColumnName("createdAtdate");

                entity.Property(e => e.ParentId).HasColumnName("parentId");

                entity.Property(e => e.PostId).HasColumnName("postId");

                entity.Property(e => e.Published).HasColumnName("published");

                entity.Property(e => e.PublishedAtdate)
                    .HasColumnType("datetime")
                    .HasColumnName("publishedAtdate");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("title");

                entity.HasOne(d => d.Parent)
                    .WithMany(p => p.InverseParent)
                    .HasForeignKey(d => d.ParentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_post_comment_Topost_comment");

                entity.HasOne(d => d.Post)
                    .WithMany(p => p.PostComment)
                    .HasForeignKey(d => d.PostId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_post_comment_ToBlogPost");
            });

            modelBuilder.Entity<Publication>(entity =>
            {
                entity.Property(e => e.Books)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("books")
                    .IsFixedLength();

                entity.Property(e => e.Ebooks)
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnName("ebooks")
                    .IsFixedLength();

                entity.Property(e => e.PublicationId).HasColumnName("Publication_Id");

                entity.HasOne(d => d.PublicationNavigation)
                    .WithMany(p => p.Publication)
                    .HasForeignKey(d => d.PublicationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Publication_ToResource");
            });

            modelBuilder.Entity<Resource>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("Name ");

                entity.Property(e => e.ResCategoryId)
                    .IsRequired()
                    .HasColumnType("ntext")
                    .HasColumnName("Res_CategoryId");
            });

            modelBuilder.Entity<ResourceAgeRange>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<ResourceAttachment>(entity =>
            {
                entity.Property(e => e.FileName).IsRequired();

                entity.Property(e => e.FilePath).IsRequired();

                entity.HasOne(d => d.Language)
                    .WithMany(p => p.ResourceAttachment)
                    .HasForeignKey(d => d.LanguageId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ResourceAttachment_ToLanguage");

                entity.HasOne(d => d.Resource)
                    .WithMany(p => p.ResourceAttachment)
                    .HasForeignKey(d => d.ResourceId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ResourceAttachment_ToResource");
            });

            modelBuilder.Entity<ResourceCategory>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<ResourceTag>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                entity.Property(e => e.TagName)
                    .IsRequired()
                    .HasColumnType("text");

                entity.HasOne(d => d.IdNavigation)
                    .WithOne(p => p.ResourceTag)
                    .HasForeignKey<ResourceTag>(d => d.Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ResourceTag_ToResourceCategory");
            });

            modelBuilder.Entity<Tag>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("name");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}