// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class Employment
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long EmployerId { get; set; }
        public long EmployLearningId { get; set; }
        public long EmployTrainId { get; set; }

        public virtual EmployLearning EmployLearning { get; set; }
        public virtual EmployTraining EmployTrain { get; set; }
        public virtual Employer Employer { get; set; }
    }
}