// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class EmployLearning
    {
        public EmployLearning()
        {
            Employment = new HashSet<Employment>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public DateTime? StarDate { get; set; }
        public DateTime? EndDate { get; set; }

        public virtual ICollection<Employment> Employment { get; set; }
    }
}