// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class EmployAsd
    {
        public EmployAsd()
        {
            Employment = new HashSet<Employment>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long Asdid { get; set; }

        public virtual Employment Asd { get; set; }
        public virtual ICollection<Employment> Employment { get; set; }
    }
}