// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class PostComment
    {
        public PostComment()
        {
            InverseParent = new HashSet<PostComment>();
        }

        public long Id { get; set; }
        public long PostId { get; set; }
        public long ParentId { get; set; }
        public byte[] Title { get; set; }
        public byte Published { get; set; }
        public DateTime CreatedAtdate { get; set; }
        public DateTime PublishedAtdate { get; set; }
        public string Content { get; set; }

        public virtual PostComment Parent { get; set; }
        public virtual BlogPost Post { get; set; }
        public virtual ICollection<PostComment> InverseParent { get; set; }
    }
}