// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class Publication
    {
        public long Id { get; set; }
        public string Ebooks { get; set; }
        public string Books { get; set; }
        public long PublicationId { get; set; }

        public virtual Resource PublicationNavigation { get; set; }
    }
}