// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class Resource
    {
        public Resource()
        {
            Publication = new HashSet<Publication>();
            ResourceAttachment = new HashSet<ResourceAttachment>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string ResCategoryId { get; set; }

        public virtual ICollection<Publication> Publication { get; set; }
        public virtual ICollection<ResourceAttachment> ResourceAttachment { get; set; }
    }
}