// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class ResourceTag
    {
        public long Id { get; set; }
        public string TagName { get; set; }

        public virtual ResourceCategory IdNavigation { get; set; }
    }
}