// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class ResourceAttachment
    {
        public long Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public long LanguageId { get; set; }
        public long FileSize { get; set; }
        public int? DateUpLoad { get; set; }
        public long ResourceId { get; set; }

        public virtual Language Language { get; set; }
        public virtual Resource Resource { get; set; }
    }
}