// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class Table1
    {
        public int Id { get; set; }
        public double? Ink { get; set; }
    }
}