// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShareProject.Models
{
    public partial class Tag
    {
        public Tag()
        {
            Tagpost = new HashSet<Tagpost>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public virtual ICollection<Tagpost> Tagpost { get; set; }
    }
}